ALTER TABLE users
    ADD COLUMN IF NOT EXISTS full_name VARCHAR(120),
    ADD COLUMN IF NOT EXISTS bio TEXT,
    ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS website VARCHAR(255),
    ADD COLUMN IF NOT EXISTS linked_in VARCHAR(255),
    ADD COLUMN IF NOT EXISTS github VARCHAR(255),
    ADD COLUMN IF NOT EXISTS location VARCHAR(120);
