CREATE TABLE leaderboard_entries (id BIGSERIAL PRIMARY KEY, 
user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE, 
solved_count INTEGER NOT NULL DEFAULT 0, total_submissions INTEGER NOT NULL DEFAULT 0, 
accepted_submissions INTEGER NOT NULL DEFAULT 0, score DOUBLE PRECISION NOT NULL DEFAULT 0, 
rank INTEGER, updated_at TIMESTAMP NOT NULL DEFAULT now());

